# Downloads OpenJFX jars into dist\lib so `ant build`/`ant fatjar` can compile the JavaFX-dependent
# GUI code. This OpenJDK build doesn't bundle JavaFX (only Oracle's JDK 10 did), and dist\ is wiped
# by `ant clean` / regenerated by `ant build`, so this needs to be re-run after a clean build.
#
# Usage: run `ant build` (or `ant fatjar`) once first so dist\lib exists, then run this script,
# then run `ant build` (or `ant fatjar`) again.

$ErrorActionPreference = "Stop"

$destDir = Join-Path $PSScriptRoot "dist\lib"
if (-not (Test-Path $destDir)) {
    New-Item -ItemType Directory -Force -Path $destDir | Out-Null
}

$modules = @("javafx-base", "javafx-graphics", "javafx-controls", "javafx-fxml", "javafx-media", "javafx-web", "javafx-swing")
$version = "11"

foreach ($mod in $modules) {
    $url = "https://repo1.maven.org/maven2/org/openjfx/$mod/$version/$mod-$version-win.jar"
    $dest = Join-Path $destDir "$mod.jar"
    Write-Host "Downloading $mod..."
    Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing
}

Write-Host "Done. JavaFX jars are in $destDir"
Write-Host "Now run: ant build  (or ant fatjar)"
